Added the RCE_API_HOST environment variable
instructure/canvas-rce-api pull request #5
Opened 2019-05-29 01:16 UTC by jrherskovic-mda

Hi,

We run our Canvas instances on servers not directly exposed to the internet and without publicly routable addresses. They are behind a load balancer/nat appliance.

The canvas-rce-api proxy was getting 127.0.0.1 when calling `request.get("host")` which meant that the flies browser was getting unusable JSON from `app/api/folders.js` and unable to work.

To get around the problem, we added an environment variable `RCE_API_HOST` that allows the sysadmin to force the public URL to a setting of their choosing. If the variable is not set, the previous behavior (using `request.get("host")`) is preserved.

Best,
Jorge

2019-05-29 01:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/canvas-rce-api?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/canvas-rce-api?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/canvas-rce-api?pullRequest=5) it.</sub>

2019-05-30 14:26 UTC, claydiffrient commented
@jrherskovic-mda It seems that this patchset doesn't pass the test suite.  I'm getting the following two errors:

```
  272 passing (615ms)
  2 failing

  1) Link API response handlers
       successful canvas responses
         bookmark construction
           keeps the request's protocol and host:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(bookmark.match("^http://rce.example"))

      at Context.it (test/service/api/linksResponseHandler.test.js:103:16)

  2) packageBookmark
       forms corect url:

      AssertionError [ERR_ASSERTION]: 'http://false/a/b/c?id=47&bookmark=canvasurl' == 'http://somehost:3000/a/b/c?id=47&bookmark=canvasurl'
      + expected - actual

      -http://false/a/b/c?id=47&bookmark=canvasurl
      +http://somehost:3000/a/b/c?id=47&bookmark=canvasurl
      
      at Context.it (test/service/api/packageBookmark.test.js:27:5)
```

Would you take a look at those and make adjustments as needed?  You should be able to run the test suite by running `npm test` within the repo.

2019-05-30 18:54 UTC, jherskovic commented
Fixed the issue. Sorry about that - node isn't my strong suit. That said, the test suite behaves differently on my machine. Could you please verify again?

2019-06-03 14:23 UTC, claydiffrient requested changes

2019-06-03 14:23 UTC, claydiffrient commented on app/api/packageBookmark.js
> +    const myUrl = process.env.RCE_API_HOST || request.get("Host");
I think the test here is wrong.  Let's be consistent and make this lowercase.  However, a change should be made at https://github.com/instructure/canvas-rce-api/blob/master/test/service/api/linksResponseHandler.test.js#L84 so that the test doesn't specify the need for `Host` since `request.get()` is case insensitive.  Perhaps that line could be adjusted to be lowercase or to even handle both variations, `host` and `Host`.

2019-09-16 17:08 UTC, claydiffrient commented
@jherskovic I'm just auditing stuff that's outstanding here.  There hasn't been any response since I last reviewed on June 3.  Are you still interested in the getting this merged in?

2019-09-16 17:16 UTC, jherskovic commented
> @jherskovic I'm just auditing stuff that's outstanding here. There hasn't been any response since I last reviewed on June 3. Are you still interested in the getting this merged in?

Yes, definitely. Sorry - I didn't realize that your comments on the test were meant for me. I can certainly attempt to fix the test, if that's what you need.

2019-09-16 17:35 UTC, jrherskovic-mda commented
Ended up ignoring casing of the Host variable - please LMK if this is acceptable.

2019-09-30 23:45 UTC, diegotejadav commented
Hi, as @claydiffrient said in https://github.com/instructure/canvas-rce-api/pull/5#issuecomment-531869048, is this change going to be applied?, we're working Apache with a proxy to serve the RCE API and the problem is the same, so we need to be able to pass the **RCE_API_HOST** in the .env

2019-09-30 23:55 UTC, thattejada approved these changes

2019-10-17 03:21 UTC, thattejada approved these changes
We have tested this changes in our production environment and they work as expected, these changes are required when working with a proxy to serve the RCE API that is working from 127.0.0.1:3000, that way with the RCE_API_HOST config in the .env file everything works.

2020-02-14 09:54 UTC, Gao-Jun commented
This PR is great. I tested in out production environment.
I suggest this PR be accepted except "package-lock.json"

2026-05-20 20:10 UTC, claydiffrient reviewed
This is pretty old... and I don't work at Instructure anymore... trying to remove this from my review plate, but I'm not sure I can.

2026-05-20 20:53 UTC, closed without merging

2026-05-20 20:54 UTC, jrherskovic-mda commented
Closed it at @claydiffrient 's request, since it seems a change added the functionality anyway.